import Head from 'next/head'
import Books from '@/components/book/books'
import axios from 'axios'
import { GetServerSideProps } from 'next'


export default function Home({ books}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Books books={books} />
      </div>
    </>
  )
}

export const getServerSideProps = async() => {
 try {
  const { data } = await axios(`${process.env.NEXT_PUBLIC_STRAPI_API}/api/books?populate=cover`);
  console.log(data.data);
  return {
   props: {
    books: data.data,
    error: null,
   }
  }
  
 } catch (error:any) {
  return {
    props: {
      books: null,
      error: error.message,
    }
  }
 }
}